version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - media:/vol/web/media
      - static:/vol/web/static
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SEC_KEY=s)#6qn9mlbof$mt!he(s#yt9v69)_^jp4i+jr@y8b*&sv#r1uz
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=mypassword
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword

volumes:
  media:
  static:
  pgdata: